# @formatter:off

# App configuration.
server.port=9080
spring.application.name=service-todo

# Logging configuration.
logging.level.com.eurodyn.qlack.observability.todo=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level){spring} %-30.30logger - %msg%n
