# @formatter:off

# App configuration.
server.port=9081
spring.application.name=service-timeauthority

# Logging configuration.
logging.level.com.eurodyn.qlack.observability.timeauthority=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level){spring} %-30.30logger - %msg%n

# OTEL configuration.
# Disable process.command_args resource attribute to avoid exceeding Mimir's 2048 character limit
otel.resource.attributes.process.command_args=

# Include all available metrics (including custom ones), and define where the OTLP exporter should send them.
management.endpoints.web.exposure.include=*
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.otlp.metrics.export.step=1s
